# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: canonical_transcription.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='canonical_transcription.proto',
  package='fonti40',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x63\x61nonical_transcription.proto\x12\x07\x66onti40\"9\n\x1b\x43\x61nonicalTokenEventProperty\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"]\n\x13\x43\x61nonicalTokenEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x38\n\nproperties\x18\x02 \x03(\x0b\x32$.fonti40.CanonicalTokenEventProperty\"\xa7\x02\n\x0e\x43\x61nonicalToken\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x02\x12\x38\n\x04type\x18\x04 \x01(\x0e\x32*.fonti40.CanonicalToken.CanonicalTokenType\x12,\n\x06\x65vents\x18\x05 \x03(\x0b\x32\x1c.fonti40.CanonicalTokenEvent\"y\n\x12\x43\x61nonicalTokenType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bPUNCTUATION\x10\x01\x12\x11\n\rPRONUNCIATION\x10\x02\x12\x0f\n\x0bVOCAL_EVENT\x10\x03\x12\x12\n\x0eINCIDENT_EVENT\x10\x04\x12\r\n\tGAP_EVENT\x10\x05\"\x89\x02\n\x12\x43\x61nonicalUtterance\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x02\x12\x0c\n\x04note\x18\x05 \x01(\t\x12&\n\x05words\x18\x06 \x03(\x0b\x32\x17.fonti40.CanonicalToken\x12\x33\n\x12words_before_start\x18\x07 \x03(\x0b\x32\x17.fonti40.CanonicalToken\x12\x30\n\x0fwords_after_end\x18\x08 \x03(\x0b\x32\x17.fonti40.CanonicalToken\x12\x12\n\nspeaker_id\x18\t \x01(\t\"I\n\x16\x43\x61nonicalTranscription\x12/\n\nutterances\x18\x02 \x03(\x0b\x32\x1b.fonti40.CanonicalUtteranceb\x06proto3'
)



_CANONICALTOKEN_CANONICALTOKENTYPE = _descriptor.EnumDescriptor(
  name='CanonicalTokenType',
  full_name='fonti40.CanonicalToken.CanonicalTokenType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUNCTUATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRONUNCIATION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOCAL_EVENT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INCIDENT_EVENT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAP_EVENT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=371,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_CANONICALTOKEN_CANONICALTOKENTYPE)


_CANONICALTOKENEVENTPROPERTY = _descriptor.Descriptor(
  name='CanonicalTokenEventProperty',
  full_name='fonti40.CanonicalTokenEventProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='fonti40.CanonicalTokenEventProperty.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='fonti40.CanonicalTokenEventProperty.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=99,
)


_CANONICALTOKENEVENT = _descriptor.Descriptor(
  name='CanonicalTokenEvent',
  full_name='fonti40.CanonicalTokenEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='fonti40.CanonicalTokenEvent.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='fonti40.CanonicalTokenEvent.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=194,
)


_CANONICALTOKEN = _descriptor.Descriptor(
  name='CanonicalToken',
  full_name='fonti40.CanonicalToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='fonti40.CanonicalToken.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='fonti40.CanonicalToken.start_time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='fonti40.CanonicalToken.end_time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='fonti40.CanonicalToken.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='fonti40.CanonicalToken.events', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CANONICALTOKEN_CANONICALTOKENTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=492,
)


_CANONICALUTTERANCE = _descriptor.Descriptor(
  name='CanonicalUtterance',
  full_name='fonti40.CanonicalUtterance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fonti40.CanonicalUtterance.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='fonti40.CanonicalUtterance.language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='fonti40.CanonicalUtterance.start_time', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='fonti40.CanonicalUtterance.end_time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='note', full_name='fonti40.CanonicalUtterance.note', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='words', full_name='fonti40.CanonicalUtterance.words', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='words_before_start', full_name='fonti40.CanonicalUtterance.words_before_start', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='words_after_end', full_name='fonti40.CanonicalUtterance.words_after_end', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speaker_id', full_name='fonti40.CanonicalUtterance.speaker_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=760,
)


_CANONICALTRANSCRIPTION = _descriptor.Descriptor(
  name='CanonicalTranscription',
  full_name='fonti40.CanonicalTranscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterances', full_name='fonti40.CanonicalTranscription.utterances', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=835,
)

_CANONICALTOKENEVENT.fields_by_name['properties'].message_type = _CANONICALTOKENEVENTPROPERTY
_CANONICALTOKEN.fields_by_name['type'].enum_type = _CANONICALTOKEN_CANONICALTOKENTYPE
_CANONICALTOKEN.fields_by_name['events'].message_type = _CANONICALTOKENEVENT
_CANONICALTOKEN_CANONICALTOKENTYPE.containing_type = _CANONICALTOKEN
_CANONICALUTTERANCE.fields_by_name['words'].message_type = _CANONICALTOKEN
_CANONICALUTTERANCE.fields_by_name['words_before_start'].message_type = _CANONICALTOKEN
_CANONICALUTTERANCE.fields_by_name['words_after_end'].message_type = _CANONICALTOKEN
_CANONICALTRANSCRIPTION.fields_by_name['utterances'].message_type = _CANONICALUTTERANCE
DESCRIPTOR.message_types_by_name['CanonicalTokenEventProperty'] = _CANONICALTOKENEVENTPROPERTY
DESCRIPTOR.message_types_by_name['CanonicalTokenEvent'] = _CANONICALTOKENEVENT
DESCRIPTOR.message_types_by_name['CanonicalToken'] = _CANONICALTOKEN
DESCRIPTOR.message_types_by_name['CanonicalUtterance'] = _CANONICALUTTERANCE
DESCRIPTOR.message_types_by_name['CanonicalTranscription'] = _CANONICALTRANSCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanonicalTokenEventProperty = _reflection.GeneratedProtocolMessageType('CanonicalTokenEventProperty', (_message.Message,), {
  'DESCRIPTOR' : _CANONICALTOKENEVENTPROPERTY,
  '__module__' : 'canonical_transcription_pb2'
  # @@protoc_insertion_point(class_scope:fonti40.CanonicalTokenEventProperty)
  })
_sym_db.RegisterMessage(CanonicalTokenEventProperty)

CanonicalTokenEvent = _reflection.GeneratedProtocolMessageType('CanonicalTokenEvent', (_message.Message,), {
  'DESCRIPTOR' : _CANONICALTOKENEVENT,
  '__module__' : 'canonical_transcription_pb2'
  # @@protoc_insertion_point(class_scope:fonti40.CanonicalTokenEvent)
  })
_sym_db.RegisterMessage(CanonicalTokenEvent)

CanonicalToken = _reflection.GeneratedProtocolMessageType('CanonicalToken', (_message.Message,), {
  'DESCRIPTOR' : _CANONICALTOKEN,
  '__module__' : 'canonical_transcription_pb2'
  # @@protoc_insertion_point(class_scope:fonti40.CanonicalToken)
  })
_sym_db.RegisterMessage(CanonicalToken)

CanonicalUtterance = _reflection.GeneratedProtocolMessageType('CanonicalUtterance', (_message.Message,), {
  'DESCRIPTOR' : _CANONICALUTTERANCE,
  '__module__' : 'canonical_transcription_pb2'
  # @@protoc_insertion_point(class_scope:fonti40.CanonicalUtterance)
  })
_sym_db.RegisterMessage(CanonicalUtterance)

CanonicalTranscription = _reflection.GeneratedProtocolMessageType('CanonicalTranscription', (_message.Message,), {
  'DESCRIPTOR' : _CANONICALTRANSCRIPTION,
  '__module__' : 'canonical_transcription_pb2'
  # @@protoc_insertion_point(class_scope:fonti40.CanonicalTranscription)
  })
_sym_db.RegisterMessage(CanonicalTranscription)


# @@protoc_insertion_point(module_scope)
